version: "3"
services: 
    nginx:
        image: ngnix:stable-alpine
        ports: 
            - "80:80"
    node-app:
        build:
            context: .
            args:
                NODE_ENV: production
        environment: 
            - NODE_ENV=production
        command: node index.js