version: "3"
services:
    watchtower:
        image: containrrr/watchtower 
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        environment: 
            - WATCHTOWER_TRACE=true
            - WATCHTOWER_DEBUG=true
            - WATCHTOWER_POLL_INTERVAL=50
        command: "app_node-app_1"